//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopiphone
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        public int MobileId { get; set; }
        public string IMEI { get; set; }
        public string Model { get; set; }
        public string Warranty { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string Picture { get; set; }
        public string Brand { get; set; }
    }
}
